print("RESUME")
print("Fill the form below please!")
firstName = input("First name: ")
lastName = input("Last Name: ")
age = int(input("Age: "))
sex = input("Sex: ")
stateOfOrigin = input("State of Origin: ")
town = input("Town: ")
profile = input("Profile: ")
skillsSummary = input("Skills Summary: ")
educations = input("Educations with Date: ")
certificates = input("Certifications: ")
workExperience = input("Work Experience: ")
activitiesAndHobby = input("Activities and Hobby: ")
languages = input("Languages: ")
referees1 = input("Referee 1: ")
referees2 = input("Referee 2: ")
